### ISSUE TITLE
Hi, David

### ISSUE THREAD

**Issue by gas3** [uplo-tech/uplo-ui#1]
Hi, David
Thanks for connecting with me.

Please reach out to me.
live:valor312_1

**Comment by gas3** [comment]
Hi, David
If you see the above message, please reply at here.

**Comment by DavidMGilbert** [comment]
Ahh ok, will do :)

**Comment by gas3** [comment]
It's the Skype ID. Please ping me.

**Comment by DavidMGilbert** [comment]
Going to delete
